[simulation]
config = "examples/cartpole/config/simulation.toml"

[[zone]]
name = "SensoryCortex"
blueprints = "examples/cartpole/config/zones/SensoryCortex/blueprints.toml"
anatomy = "examples/cartpole/config/zones/SensoryCortex/anatomy.toml"
io = "examples/cartpole/config/zones/SensoryCortex/io.toml"
shard = "examples/cartpole/config/zones/SensoryCortex/shard.toml"
baked_dir = "examples/cartpole/baked/SensoryCortex/"

[[zone]]
name = "HiddenCortex"
blueprints = "examples/cartpole/config/zones/HiddenCortex/blueprints.toml"
anatomy = "examples/cartpole/config/zones/HiddenCortex/anatomy.toml"
io = "examples/cartpole/config/zones/HiddenCortex/io.toml"
shard = "examples/cartpole/config/zones/HiddenCortex/shard.toml"
baked_dir = "examples/cartpole/baked/HiddenCortex/"

[[zone]]
name = "MotorCortex"
blueprints = "examples/cartpole/config/zones/MotorCortex/blueprints.toml"
anatomy = "examples/cartpole/config/zones/MotorCortex/anatomy.toml"
io = "examples/cartpole/config/zones/MotorCortex/io.toml"
shard = "examples/cartpole/config/zones/MotorCortex/shard.toml"
baked_dir = "examples/cartpole/baked/MotorCortex/"

[[connection]]
from = "SensoryCortex"
to = "HiddenCortex"
output_matrix = "sensory_out"
width = 8
height = 8
entry_z = "top"         # [!] Призрачные аксоны прорастут с потолка (Z=63)
target_type = "All"
growth_steps = 50       # Растут вниз до дна

[[connection]]
from = "HiddenCortex"
to = "MotorCortex"
output_matrix = "hidden_out"
width = 8
height = 8
entry_z = "top"         # [!] Снова инжектируем сигнал в потолок
target_type = "All"
growth_steps = 50
