[[input]]
name = "env_sensors"
zone = "SensoryCortex"
width = 16
height = 16
entry_z = "top"
target_type = "L4_spiny_VISp"
growth_steps = 125
empty_pixel = "nearest"
stride = 1

[[output]]
name = "sensory_out"
zone = "SensoryCortex"
width = 16
height = 16
target_type = "L4_spiny_VISp"
stride = 1
